name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          echo "Creating new GitHub release for tag ${{ github.ref }}"
          gh release create NEW_TAG_NAME --title "Release ${{ github.ref }}" --notes "Release notes for ${{ github.ref }}"
